apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cw2-server
  template:
    metadata:
      labels:
        app: cw2-server
    spec:
      containers:
      - name: cw2-server
        image: euanmunro/cw2-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      imagePullSecrets:
      - name: dockerhub-credentials
