apiVersion: v1
kind: Service
metadata:
  name: cw2-server-service
spec:
  type: NodePort
  ports:
    - port: 80           # The port the service is exposed on
      targetPort: 8080   # The port your application is listening on
      nodePort: 30080    # Optional: Specific NodePort to expose
  selector:
    app: cw2-server
