apiVersion: v1
kind: Service
metadata:
  name: cw2-server-service
spec:
  type: LoadBalancer  # Exposes the service outside the cluster
  selector:
    app: cw2-server
  ports:
  - protocol: TCP
    port: 80           # Port accessible externally
    targetPort: 8080   # Port on the container
